/**
 * Startrecept — svensk vardagsmat.
 *
 * Allt innehåll är originalskrivet för den här appen. Inga receptexter är
 * kopierade från receptsajter eller kokböcker; det handlar dessutom om rätter
 * som är allmängods i svenska kök sedan generationer.
 *
 * Mängderna är satta för att vara *realistiska att handla*, inte för att vara
 * kulinariskt eleganta. Ett recept som säger "en skvätt grädde" går inte att
 * omsätta i en förpackning.
 *
 * Taggarna används av veckoplaneraren för filtrering och variation.
 */

import type { Recipe, RecipeIngredient, RecipeUnit } from './types.ts'

type Spec = [ingredientId: string, value: number, unit: RecipeUnit, optional?: true]

function ingredients(specs: Spec[]): RecipeIngredient[] {
  return specs.map(([ingredientId, value, unit, optional]) => ({
    ingredientId,
    quantity: { value, unit },
    optional: optional === true,
  }))
}

interface Draft {
  id: string
  name: string
  description: string
  servings: number
  prep: number
  cook: number
  tags: string[]
  items: Spec[]
  steps: string[]
}

function recipe(draft: Draft): Recipe {
  return {
    id: draft.id,
    name: draft.name,
    description: draft.description,
    servings: draft.servings,
    prepMinutes: draft.prep,
    cookMinutes: draft.cook,
    tags: draft.tags,
    ingredients: ingredients(draft.items),
    instructions: draft.steps,
  }
}

export const SEED_RECIPES: Recipe[] = [
  recipe({
    id: 'kottbullar-potatis-graddsas',
    name: 'Köttbullar med potatis, gräddsås och lingon',
    description: 'Söndagsmiddag på en vardag. Går att göra dubbel sats och frysa.',
    servings: 4,
    prep: 20,
    cook: 25,
    tags: ['husmanskost', 'barnvänligt', 'frysvänligt', 'klassiker'],
    items: [
      ['blandfars', 600, 'g'],
      ['potatis', 1, 'kg'],
      ['gul_lok', 1, 'st'],
      ['agg', 1, 'st'],
      ['strobrod', 1, 'dl'],
      ['mjolk', 1, 'dl'],
      ['vispgradde', 3, 'dl'],
      ['buljongtarning', 1, 'st'],
      ['soja', 1, 'msk'],
      ['lingonsylt', 200, 'g'],
      ['smor', 50, 'g'],
      ['salt', 2, 'tsk'],
      ['peppar', 1, 'tsk'],
    ],
    steps: [
      'Blanda ströbröd och mjölk. Låt svälla tio minuter.',
      'Riv löken fint och blanda ner med färs, ägg, salt och peppar.',
      'Rulla bollar och stek dem runt om i smör.',
      'Koka potatisen.',
      'Häll grädde och buljong i stekpannan, koka ihop och smaka av med soja.',
      'Servera med lingon.',
    ],
  }),
  recipe({
    id: 'kottfarssas-spaghetti',
    name: 'Köttfärssås med spaghetti',
    description: 'Grundreceptet som alltid går hem. Blir bättre dagen efter.',
    servings: 4,
    prep: 10,
    cook: 30,
    tags: ['husmanskost', 'billigt', 'barnvänligt', 'matlådor', 'frysvänligt'],
    items: [
      ['blandfars', 500, 'g'],
      ['spaghetti', 320, 'g'],
      ['gul_lok', 1, 'st'],
      ['vitlok', 2, 'klyfta'],
      ['krossade_tomater', 400, 'g'],
      ['tomatpure', 2, 'msk'],
      ['morot', 1, 'st'],
      ['buljongtarning', 1, 'st'],
      ['oregano', 1, 'tsk'],
      ['rapsolja', 1, 'msk'],
      ['salt', 1, 'tsk'],
      ['peppar', 1, 'tsk'],
    ],
    steps: [
      'Hacka lök, vitlök och morot fint.',
      'Bryn färsen. Tillsätt grönsakerna och stek mjuka.',
      'Rör i tomatpuré och låt den fräsa en minut.',
      'Häll i krossade tomater och buljong. Låt puttra minst tjugo minuter.',
      'Koka spaghettin och smaka av såsen.',
    ],
  }),
  recipe({
    id: 'korvstroganoff',
    name: 'Korvstroganoff med ris',
    description: 'Tjugo minuter från kylskåp till bord.',
    servings: 4,
    prep: 5,
    cook: 20,
    tags: ['husmanskost', 'billigt', 'snabbt', 'barnvänligt', 'enkelt'],
    items: [
      ['falukorv', 400, 'g'],
      ['ris', 3, 'dl'],
      ['gul_lok', 1, 'st'],
      ['tomatpure', 2, 'msk'],
      ['matlagningsgradde', 3, 'dl'],
      ['senap', 1, 'tsk'],
      ['buljongtarning', 1, 'st'],
      ['rapsolja', 1, 'msk'],
      ['salt', 1, 'tsk'],
      ['peppar', 1, 'tsk'],
    ],
    steps: [
      'Skär korven i stavar och löken i skivor.',
      'Stek korven tills den fått färg. Tillsätt löken.',
      'Rör i tomatpurén och låt fräsa.',
      'Häll i grädde, buljong och senap. Låt sjuda tio minuter.',
      'Koka riset under tiden.',
    ],
  }),
  recipe({
    id: 'falukorv-i-ugn',
    name: 'Ugnsstekt falukorv med potatismos',
    description: 'Ugnen gör jobbet. Fyllningen är valfri men höjer rätten.',
    servings: 4,
    prep: 10,
    cook: 25,
    tags: ['husmanskost', 'billigt', 'enkelt', 'barnvänligt'],
    items: [
      ['falukorv', 800, 'g'],
      ['potatis', 1, 'kg'],
      ['mjolk', 2, 'dl'],
      ['smor', 50, 'g'],
      ['senap', 2, 'msk'],
      ['ost_riven', 100, 'g', true],
      ['salt', 1, 'tsk'],
    ],
    steps: [
      'Skär snitt i korven och bred senap i skårorna.',
      'Ugn 225 grader i tjugo minuter.',
      'Koka potatisen mjuk, häll av och mosa med mjölk och smör.',
      'Strö gärna ost över korven de sista minuterna.',
    ],
  }),
  recipe({
    id: 'pannbiff-med-lok',
    name: 'Pannbiff med stekt lök och brunsås',
    description: 'Färs, lök, sås. Mer behövs inte.',
    servings: 4,
    prep: 10,
    cook: 25,
    tags: ['husmanskost', 'billigt', 'klassiker'],
    items: [
      ['blandfars', 600, 'g'],
      ['potatis', 1, 'kg'],
      ['gul_lok', 3, 'st'],
      ['strobrod', 1, 'dl'],
      ['mjolk', 1, 'dl'],
      ['matlagningsgradde', 2, 'dl'],
      ['buljongtarning', 1, 'st'],
      ['soja', 1, 'msk'],
      ['smor', 50, 'g'],
      ['salt', 2, 'tsk'],
      ['peppar', 1, 'tsk'],
    ],
    steps: [
      'Blanda färs med ströbröd, mjölk, salt och peppar. Forma platta biffar.',
      'Skiva löken och stek den långsamt gyllene i smör. Ta upp.',
      'Stek biffarna i samma panna.',
      'Häll i grädde, buljong och soja. Koka ihop till sås.',
      'Koka potatis och servera med löken över.',
    ],
  }),
  recipe({
    id: 'raggmunk-med-flask',
    name: 'Raggmunk med stekt fläsk och lingon',
    description: 'Kräver lite tålamod vid spisen, men få ingredienser.',
    servings: 4,
    prep: 20,
    cook: 25,
    tags: ['husmanskost', 'billigt', 'klassiker', 'få ingredienser'],
    items: [
      ['potatis', 800, 'g'],
      ['vetemjol', 2, 'dl'],
      ['mjolk', 5, 'dl'],
      ['agg', 2, 'st'],
      ['flask_rimmat', 400, 'g'],
      ['lingonsylt', 200, 'g'],
      ['smor', 50, 'g'],
      ['salt', 1, 'tsk'],
    ],
    steps: [
      'Vispa ihop mjöl, mjölk, ägg och salt till en slät smet. Låt stå tio minuter.',
      'Riv potatisen grovt och rör ner den precis före stekning.',
      'Stek tunna plättar i smör tills de är gyllene på båda sidor.',
      'Stek fläsket knaprigt och servera med lingon.',
    ],
  }),
  recipe({
    id: 'pytt-i-panna',
    name: 'Pytt i panna med stekt ägg',
    description: 'Byggd för rester. Byt gärna ut korven mot vad som finns.',
    servings: 4,
    prep: 15,
    cook: 20,
    tags: ['husmanskost', 'billigt', 'snabbt', 'rester', 'enkelt'],
    items: [
      ['potatis', 800, 'g'],
      ['falukorv', 400, 'g'],
      ['gul_lok', 2, 'st'],
      ['agg', 4, 'st'],
      ['rodbetor', 200, 'g', true],
      ['smor', 50, 'g'],
      ['salt', 1, 'tsk'],
      ['peppar', 1, 'tsk'],
    ],
    steps: [
      'Tärna potatis, korv och lök i jämnstora bitar.',
      'Stek potatisen först, i omgångar så pannan inte blir överfull.',
      'Tillsätt korv och lök och stek tills allt fått färg.',
      'Stek äggen och lägg dem ovanpå.',
    ],
  }),
  recipe({
    id: 'lasagne',
    name: 'Lasagne',
    description: 'Gör gärna dubbel sats — den andra går rakt in i frysen.',
    servings: 6,
    prep: 25,
    cook: 40,
    tags: ['husmanskost', 'barnvänligt', 'frysvänligt', 'matlådor'],
    items: [
      ['blandfars', 700, 'g'],
      ['lasagneplattor', 250, 'g'],
      ['krossade_tomater', 800, 'g'],
      ['tomatpure', 2, 'msk'],
      ['gul_lok', 1, 'st'],
      ['vitlok', 2, 'klyfta'],
      ['morot', 2, 'st'],
      ['mjolk', 6, 'dl'],
      ['vetemjol', 4, 'msk'],
      ['smor', 50, 'g'],
      ['ost_riven', 200, 'g'],
      ['oregano', 1, 'msk'],
      ['salt', 2, 'tsk'],
      ['peppar', 1, 'tsk'],
    ],
    steps: [
      'Bryn färsen med hackad lök, vitlök och riven morot.',
      'Tillsätt tomatpuré, krossade tomater och oregano. Låt puttra tjugo minuter.',
      'Smält smör, vispa i mjöl och späd med mjölken till en slät bechamel.',
      'Varva köttfärssås, plattor och bechamel i en form. Avsluta med ost.',
      'Ugn 200 grader i fyrtio minuter. Låt vila tio minuter före servering.',
    ],
  }),
  recipe({
    id: 'kycklinggryta-curry',
    name: 'Kycklinggryta i curry med ris',
    description: 'Mild och barnvänlig. Öka currymängden för egen del.',
    servings: 4,
    prep: 10,
    cook: 25,
    tags: ['snabbt', 'barnvänligt', 'one-pot', 'matlådor'],
    items: [
      ['kycklingfile', 600, 'g'],
      ['ris', 3, 'dl'],
      ['gul_lok', 1, 'st'],
      ['paprika', 1, 'st'],
      ['matlagningsgradde', 3, 'dl'],
      ['curry', 2, 'tsk'],
      ['buljongtarning', 1, 'st'],
      ['rapsolja', 1, 'msk'],
      ['salt', 1, 'tsk'],
    ],
    steps: [
      'Skär kycklingen i bitar och bryn den i olja.',
      'Tillsätt hackad lök och strimlad paprika.',
      'Strö över curry och låt fräsa en halv minut.',
      'Häll i grädde och buljong. Sjud femton minuter.',
      'Koka riset under tiden.',
    ],
  }),
  recipe({
    id: 'fiskgratang',
    name: 'Fiskgratäng med potatismos',
    description: 'Vitfisk i ugn. Går lika bra med torsk som med sej.',
    servings: 4,
    prep: 15,
    cook: 25,
    tags: ['fisk', 'ugn', 'barnvänligt'],
    items: [
      ['torskfile', 600, 'g'],
      ['potatis', 1, 'kg'],
      ['matlagningsgradde', 3, 'dl'],
      ['ost_riven', 100, 'g'],
      ['dill', 20, 'g'],
      ['citron', 1, 'st'],
      ['mjolk', 2, 'dl'],
      ['smor', 50, 'g'],
      ['salt', 2, 'tsk'],
      ['peppar', 1, 'tsk'],
    ],
    steps: [
      'Lägg fisken i en smord form, salta och peppra.',
      'Häll över grädden, strö på dill och riven ost.',
      'Ugn 200 grader i tjugofem minuter.',
      'Koka och mosa potatisen med mjölk och smör.',
      'Pressa citron över fisken vid servering.',
    ],
  }),
  recipe({
    id: 'ugnslax-potatis',
    name: 'Ugnsbakad lax med kokt potatis',
    description: 'Nästan ingen handpåläggning. Laxen blir saftig i låg ugn.',
    servings: 4,
    prep: 10,
    cook: 25,
    tags: ['fisk', 'enkelt', 'ugn', 'nyttigt'],
    items: [
      ['laxfile', 600, 'g'],
      ['potatis', 800, 'g'],
      ['creme_fraiche', 2, 'dl'],
      ['dill', 20, 'g'],
      ['citron', 1, 'st'],
      ['smor', 25, 'g'],
      ['salt', 2, 'tsk'],
      ['peppar', 1, 'tsk'],
    ],
    steps: [
      'Lägg laxen i en form, salta och peppra.',
      'Ugn 175 grader i tjugo till tjugofem minuter.',
      'Koka potatisen.',
      'Rör ihop crème fraiche med hackad dill och citronsaft.',
    ],
  }),
  recipe({
    id: 'artsoppa-pannkakor',
    name: 'Ärtsoppa och pannkakor',
    description: 'Torsdagsmat. Soppan blir bara bättre av att stå.',
    servings: 6,
    prep: 15,
    cook: 90,
    tags: ['husmanskost', 'billigt', 'klassiker', 'frysvänligt'],
    items: [
      ['gula_artor', 5, 'dl'],
      ['flask_rimmat', 300, 'g'],
      ['gul_lok', 1, 'st'],
      ['morot', 2, 'st'],
      ['senap', 2, 'msk'],
      ['timjan', 1, 'tsk'],
      ['vetemjol', 3, 'dl'],
      ['mjolk', 6, 'dl'],
      ['agg', 3, 'st'],
      ['smor', 50, 'g'],
      ['salt', 2, 'tsk'],
    ],
    steps: [
      'Blötlägg ärtorna över natten. Skölj av dem.',
      'Koka ärtorna med fläsk, hackad lök, morot och timjan i cirka en och en halv timme.',
      'Vispa ihop pannkakssmet av mjöl, mjölk, ägg och salt. Låt vila.',
      'Stek pannkakor i smör medan soppan blir klar.',
      'Servera soppan med senap.',
    ],
  }),
  recipe({
    id: 'makaroner-kottbullar',
    name: 'Makaroner och köttbullar',
    description: 'Den enklaste vardagsmiddagen som finns.',
    servings: 4,
    prep: 10,
    cook: 20,
    tags: ['billigt', 'snabbt', 'barnvänligt', 'få ingredienser', 'enkelt'],
    items: [
      ['blandfars', 500, 'g'],
      ['pasta', 320, 'g'],
      ['agg', 1, 'st'],
      ['strobrod', 1, 'dl'],
      ['mjolk', 1, 'dl'],
      ['ketchup', 1, 'dl'],
      ['smor', 25, 'g'],
      ['salt', 2, 'tsk'],
      ['peppar', 1, 'tsk'],
    ],
    steps: [
      'Blanda färsen med ägg, ströbröd, mjölk, salt och peppar.',
      'Rulla små bullar och stek dem runt om.',
      'Koka makaronerna.',
    ],
  }),
  recipe({
    id: 'pasta-skinksas',
    name: 'Pasta med skinksås',
    description: 'Femton minuter, och nästan allt finns redan hemma.',
    servings: 4,
    prep: 5,
    cook: 15,
    tags: ['billigt', 'snabbt', 'barnvänligt', 'enkelt', 'få ingredienser'],
    items: [
      ['skinka_tarnad', 250, 'g'],
      ['pasta', 320, 'g'],
      ['matlagningsgradde', 3, 'dl'],
      ['gul_lok', 1, 'st'],
      ['buljongtarning', 1, 'st'],
      ['arter_frysta', 200, 'g'],
      ['rapsolja', 1, 'msk'],
      ['peppar', 1, 'tsk'],
    ],
    steps: [
      'Koka pastan.',
      'Fräs hackad lök och skinka i olja.',
      'Häll i grädde och smula i buljongtärningen. Koka ihop några minuter.',
      'Rör ner ärterna sista minuten.',
    ],
  }),
  recipe({
    id: 'tacogratang',
    name: 'Tacogratäng',
    description: 'Fredagsmyset i ugnsform. Mindre disk än tacos.',
    servings: 4,
    prep: 15,
    cook: 25,
    tags: ['barnvänligt', 'ugn', 'fredagsmys'],
    items: [
      ['blandfars', 500, 'g'],
      ['tortilla', 8, 'st'],
      ['tacokrydda', 1, 'pkt'],
      ['krossade_tomater', 400, 'g'],
      ['majs', 200, 'g'],
      ['paprika', 1, 'st'],
      ['creme_fraiche', 2, 'dl'],
      ['ost_riven', 200, 'g'],
      ['gul_lok', 1, 'st'],
      ['rapsolja', 1, 'msk'],
    ],
    steps: [
      'Bryn färsen med hackad lök och paprika.',
      'Tillsätt tacokrydda, krossade tomater och majs. Låt puttra tio minuter.',
      'Varva sönderrivna tortillabröd med färsröran i en form.',
      'Toppa med crème fraiche och ost. Ugn 200 grader i tjugo minuter.',
    ],
  }),
  recipe({
    id: 'chili-con-carne',
    name: 'Chili con carne',
    description: 'Blir bättre ju längre den får stå. Frys gärna halva satsen.',
    servings: 6,
    prep: 15,
    cook: 40,
    tags: ['one-pot', 'frysvänligt', 'matlådor', 'billigt'],
    items: [
      ['blandfars', 600, 'g'],
      ['kidneybonor', 400, 'g'],
      ['krossade_tomater', 800, 'g'],
      ['gul_lok', 2, 'st'],
      ['vitlok', 3, 'klyfta'],
      ['paprika', 2, 'st'],
      ['majs', 200, 'g'],
      ['tomatpure', 2, 'msk'],
      ['chilipulver', 2, 'tsk'],
      ['spiskummin', 2, 'tsk'],
      ['buljongtarning', 1, 'st'],
      ['ris', 3, 'dl'],
      ['rapsolja', 1, 'msk'],
      ['salt', 2, 'tsk'],
    ],
    steps: [
      'Bryn färsen. Tillsätt hackad lök, vitlök och paprika.',
      'Rör i tomatpuré, chili och spiskummin. Låt fräsa.',
      'Häll i krossade tomater och buljong. Sjud minst trettio minuter.',
      'Rör ner bönor och majs sista tio minuterna.',
      'Koka ris till.',
    ],
  }),
  recipe({
    id: 'shepherds-pie',
    name: 'Köttfärspaj med potatismos',
    description: 'Färssås under, mos över. Svensk variant av shepherd’s pie.',
    servings: 6,
    prep: 20,
    cook: 35,
    tags: ['ugn', 'barnvänligt', 'frysvänligt'],
    items: [
      ['blandfars', 600, 'g'],
      ['potatis', 1.2, 'kg'],
      ['gul_lok', 1, 'st'],
      ['morot', 2, 'st'],
      ['arter_frysta', 200, 'g'],
      ['krossade_tomater', 400, 'g'],
      ['buljongtarning', 1, 'st'],
      ['mjolk', 2, 'dl'],
      ['smor', 75, 'g'],
      ['ost_riven', 100, 'g'],
      ['timjan', 1, 'tsk'],
      ['salt', 2, 'tsk'],
    ],
    steps: [
      'Bryn färsen med lök och riven morot.',
      'Tillsätt tomater, buljong och timjan. Sjud tjugo minuter. Rör i ärterna.',
      'Koka potatisen och mosa med mjölk och smör.',
      'Lägg färsen i en form, bred moset över och strö på ost.',
      'Ugn 200 grader i trettiofem minuter tills ytan fått färg.',
    ],
  }),
  recipe({
    id: 'kalops',
    name: 'Kalops med kokt potatis',
    description: 'Långkok som sköter sig själv. Kryddpepparen är hela poängen.',
    servings: 6,
    prep: 15,
    cook: 120,
    tags: ['husmanskost', 'långkok', 'frysvänligt', 'klassiker'],
    items: [
      ['notkott_gryta', 800, 'g'],
      ['gul_lok', 3, 'st'],
      ['morot', 3, 'st'],
      ['kryddpeppar', 2, 'tsk'],
      ['lagerblad', 3, 'st'],
      ['buljongtarning', 2, 'st'],
      ['vetemjol', 2, 'msk'],
      ['potatis', 1, 'kg'],
      ['rapsolja', 2, 'msk'],
      ['salt', 2, 'tsk'],
    ],
    steps: [
      'Bryn köttet i omgångar. Lägg över i en gryta.',
      'Fräs lök och morot i samma panna och lägg i grytan.',
      'Tillsätt kryddpeppar, lagerblad, buljong och vatten så det täcker.',
      'Sjud under lock i cirka två timmar tills köttet är mört.',
      'Red av med mjöl utrört i lite vatten. Koka potatis till.',
    ],
  }),
  recipe({
    id: 'flaskfile-gryta',
    name: 'Fläskfilégryta med ris',
    description: 'Snabb gryta som ändå känns som helgmat.',
    servings: 4,
    prep: 15,
    cook: 20,
    tags: ['snabbt', 'one-pot'],
    items: [
      ['flaskfile', 600, 'g'],
      ['ris', 3, 'dl'],
      ['champinjoner', 250, 'g'],
      ['gul_lok', 1, 'st'],
      ['matlagningsgradde', 3, 'dl'],
      ['buljongtarning', 1, 'st'],
      ['senap', 1, 'msk'],
      ['rapsolja', 1, 'msk'],
      ['salt', 1, 'tsk'],
      ['peppar', 1, 'tsk'],
    ],
    steps: [
      'Skär filén i skivor och bryn dem hastigt. Ta upp.',
      'Stek svamp och lök i samma panna.',
      'Häll i grädde, buljong och senap. Koka ihop.',
      'Lägg tillbaka köttet och låt sjuda fem minuter. Koka ris till.',
    ],
  }),
  recipe({
    id: 'kycklinggryta-tomat',
    name: 'Kycklinggryta med tomat och paprika',
    description: 'En gryta, en kastrull ris, ingen extra disk.',
    servings: 4,
    prep: 10,
    cook: 30,
    tags: ['one-pot', 'matlådor', 'billigt'],
    items: [
      ['kycklinglarfile', 700, 'g'],
      ['ris', 3, 'dl'],
      ['krossade_tomater', 400, 'g'],
      ['paprika', 2, 'st'],
      ['gul_lok', 1, 'st'],
      ['vitlok', 2, 'klyfta'],
      ['buljongtarning', 1, 'st'],
      ['paprikapulver', 2, 'tsk'],
      ['oregano', 1, 'tsk'],
      ['rapsolja', 1, 'msk'],
      ['salt', 1, 'tsk'],
    ],
    steps: [
      'Bryn kycklingen i olja.',
      'Tillsätt lök, vitlök och strimlad paprika.',
      'Rör i paprikapulver, tomater, buljong och oregano.',
      'Sjud tjugo minuter. Koka ris under tiden.',
    ],
  }),
  recipe({
    id: 'bruna-bonor-flask',
    name: 'Stekt fläsk med bruna bönor',
    description: 'Enkel husmanskost med tydlig sötsyrlig ton.',
    servings: 4,
    prep: 5,
    cook: 20,
    tags: ['husmanskost', 'billigt', 'klassiker', 'få ingredienser'],
    items: [
      ['flask_rimmat', 500, 'g'],
      ['kidneybonor', 800, 'g'],
      ['vinager', 2, 'msk'],
      ['socker', 2, 'msk'],
      ['potatismjol', 1, 'msk'],
      ['salt', 1, 'tsk'],
    ],
    steps: [
      'Stek fläsket knaprigt.',
      'Värm bönorna med ättika och socker.',
      'Red av lätt med potatismjöl utrört i vatten.',
      'Smaka av — den ska vara både söt och syrlig.',
    ],
  }),
  recipe({
    id: 'kyckling-i-ugn-rotfrukter',
    name: 'Ugnskyckling med rotfrukter',
    description: 'En plåt, fyrtio minuter, nästan ingen disk.',
    servings: 4,
    prep: 15,
    cook: 40,
    tags: ['ugn', 'one-pot', 'nyttigt', 'enkelt'],
    items: [
      ['kycklinglarfile', 700, 'g'],
      ['potatis', 800, 'g'],
      ['morot', 4, 'st'],
      ['palsternacka', 2, 'st'],
      ['gul_lok', 2, 'st'],
      ['vitlok', 3, 'klyfta'],
      ['rapsolja', 3, 'msk'],
      ['timjan', 2, 'tsk'],
      ['salt', 2, 'tsk'],
      ['peppar', 1, 'tsk'],
    ],
    steps: [
      'Skär rotfrukterna i jämnstora bitar och lägg på en plåt.',
      'Ringla över olja, salta, peppra och strö på timjan.',
      'Lägg kycklingen ovanpå.',
      'Ugn 225 grader i cirka fyrtio minuter.',
    ],
  }),
  recipe({
    id: 'laxpasta',
    name: 'Krämig laxpasta',
    description: 'Klar på tjugo minuter och känns ändå omsorgsfull.',
    servings: 4,
    prep: 10,
    cook: 15,
    tags: ['fisk', 'snabbt', 'enkelt'],
    items: [
      ['laxfile', 500, 'g'],
      ['pasta', 320, 'g'],
      ['matlagningsgradde', 3, 'dl'],
      ['spenat_fryst', 200, 'g'],
      ['citron', 1, 'st'],
      ['vitlok', 2, 'klyfta'],
      ['buljongtarning', 1, 'st'],
      ['rapsolja', 1, 'msk'],
      ['salt', 1, 'tsk'],
      ['peppar', 1, 'tsk'],
    ],
    steps: [
      'Koka pastan.',
      'Skär laxen i bitar och stek den hastigt med vitlök.',
      'Häll i grädde, buljong och spenat. Låt sjuda några minuter.',
      'Smaka av med citron.',
    ],
  }),
  recipe({
    id: 'vegetarisk-lasagne',
    name: 'Vegetarisk lasagne med linsfärs',
    description: 'Bönor och rotfrukter i stället för färs. Mättar lika bra.',
    servings: 6,
    prep: 25,
    cook: 40,
    tags: ['vegetariskt', 'ugn', 'frysvänligt'],
    items: [
      ['lasagneplattor', 250, 'g'],
      ['kidneybonor', 800, 'g'],
      ['krossade_tomater', 800, 'g'],
      ['morot', 3, 'st'],
      ['gul_lok', 2, 'st'],
      ['vitlok', 3, 'klyfta'],
      ['tomatpure', 2, 'msk'],
      ['mjolk', 6, 'dl'],
      ['vetemjol', 4, 'msk'],
      ['smor', 50, 'g'],
      ['ost_riven', 200, 'g'],
      ['oregano', 1, 'msk'],
      ['salt', 2, 'tsk'],
    ],
    steps: [
      'Fräs lök, vitlök och riven morot mjuka.',
      'Tillsätt grovt mosade bönor, tomatpuré, krossade tomater och oregano.',
      'Sjud tjugo minuter medan du gör en bechamel av smör, mjöl och mjölk.',
      'Varva i form, toppa med ost och grädda 200 grader i fyrtio minuter.',
    ],
  }),
  recipe({
    id: 'korv-rotmos',
    name: 'Kokt korv med rotmos',
    description: 'Kålroten gör moset. Potatis ensam blir inte samma sak.',
    servings: 4,
    prep: 15,
    cook: 35,
    tags: ['husmanskost', 'billigt', 'klassiker'],
    items: [
      ['falukorv', 800, 'g'],
      ['kalrot', 1, 'st'],
      ['potatis', 600, 'g'],
      ['morot', 2, 'st'],
      ['smor', 50, 'g'],
      ['kryddpeppar', 1, 'tsk'],
      ['senap', 2, 'msk'],
      ['salt', 2, 'tsk'],
    ],
    steps: [
      'Skala och tärna kålrot, potatis och morot.',
      'Koka rotfrukterna mjuka i saltat vatten med kryddpeppar.',
      'Häll av och mosa med smör.',
      'Koka korven försiktigt i tio minuter och servera med senap.',
    ],
  }),
  recipe({
    id: 'agg-och-potatisgratang',
    name: 'Potatisgratäng med korv',
    description: 'Ugnen sköter allt. Bra när dagen redan varit lång.',
    servings: 4,
    prep: 15,
    cook: 45,
    tags: ['ugn', 'billigt', 'enkelt', 'barnvänligt'],
    items: [
      ['potatis', 1, 'kg'],
      ['falukorv', 400, 'g'],
      ['matlagningsgradde', 4, 'dl'],
      ['mjolk', 2, 'dl'],
      ['ost_riven', 150, 'g'],
      ['gul_lok', 1, 'st'],
      ['vitlok', 2, 'klyfta'],
      ['salt', 2, 'tsk'],
      ['peppar', 1, 'tsk'],
    ],
    steps: [
      'Skiva potatisen tunt och lägg den i en smord form.',
      'Varva med skivad korv och lök.',
      'Blanda grädde, mjölk, pressad vitlök, salt och peppar. Häll över.',
      'Strö på ost. Ugn 200 grader i cirka fyrtiofem minuter.',
    ],
  }),
  recipe({
    id: 'fisksoppa',
    name: 'Fisksoppa med potatis och dill',
    description: 'Mild och matig. Fungerar med vilken vit fisk som helst.',
    servings: 4,
    prep: 15,
    cook: 25,
    tags: ['fisk', 'one-pot', 'nyttigt'],
    items: [
      ['torskfile', 500, 'g'],
      ['potatis', 600, 'g'],
      ['purjolok', 1, 'st'],
      ['morot', 2, 'st'],
      ['matlagningsgradde', 3, 'dl'],
      ['buljongtarning', 2, 'st'],
      ['dill', 20, 'g'],
      ['smor', 25, 'g'],
      ['salt', 1, 'tsk'],
      ['peppar', 1, 'tsk'],
    ],
    steps: [
      'Fräs skivad purjolök och morot i smör.',
      'Tillsätt tärnad potatis, buljong och vatten. Koka tills potatisen mjuknat.',
      'Häll i grädden och lägg i fisken i bitar. Sjud fem minuter.',
      'Toppa med hackad dill.',
    ],
  }),
  recipe({
    id: 'kottfarsbiffar-brockoli',
    name: 'Färsbiffar med broccoli och potatis',
    description: 'Enkel vardagsmat med en grönsak som faktiskt blir uppäten.',
    servings: 4,
    prep: 15,
    cook: 20,
    tags: ['billigt', 'snabbt', 'nyttigt'],
    items: [
      ['blandfars', 500, 'g'],
      ['potatis', 800, 'g'],
      ['broccoli', 1, 'st'],
      ['gul_lok', 1, 'st'],
      ['agg', 1, 'st'],
      ['strobrod', 1, 'dl'],
      ['mjolk', 1, 'dl'],
      ['smor', 25, 'g'],
      ['salt', 2, 'tsk'],
      ['peppar', 1, 'tsk'],
    ],
    steps: [
      'Blanda färs, riven lök, ägg, ströbröd och mjölk. Forma biffar.',
      'Stek biffarna i smör.',
      'Koka potatisen och ångkoka broccolin några minuter.',
    ],
  }),
  recipe({
    id: 'pannkakor-middag',
    name: 'Ugnspannkaka med fläsk',
    description: 'En plåt i ugnen i stället för en halvtimme vid stekpannan.',
    servings: 4,
    prep: 10,
    cook: 35,
    tags: ['billigt', 'ugn', 'barnvänligt', 'få ingredienser'],
    items: [
      ['vetemjol', 4, 'dl'],
      ['mjolk', 8, 'dl'],
      ['agg', 4, 'st'],
      ['flask_rimmat', 300, 'g'],
      ['lingonsylt', 200, 'g'],
      ['smor', 25, 'g'],
      ['salt', 1, 'tsk'],
    ],
    steps: [
      'Vispa ihop mjöl, mjölk, ägg och salt. Låt smeten vila tio minuter.',
      'Stek fläsket och lägg det på en smord plåt.',
      'Häll smeten över och grädda 225 grader i cirka trettiofem minuter.',
      'Servera med lingon.',
    ],
  }),
  recipe({
    id: 'vegetarisk-gryta-kokos',
    name: 'Grönsaksgryta med kokos och ris',
    description: 'Vegetariskt utan att kännas som en kompromiss.',
    servings: 4,
    prep: 15,
    cook: 25,
    tags: ['vegetariskt', 'one-pot', 'billigt', 'matlådor'],
    items: [
      ['kokosmjolk', 400, 'ml'],
      ['kidneybonor', 400, 'g'],
      ['ris', 3, 'dl'],
      ['morot', 3, 'st'],
      ['paprika', 2, 'st'],
      ['gul_lok', 1, 'st'],
      ['vitlok', 2, 'klyfta'],
      ['spenat_fryst', 200, 'g'],
      ['curry', 2, 'tsk'],
      ['buljongtarning', 1, 'st'],
      ['rapsolja', 1, 'msk'],
      ['salt', 1, 'tsk'],
    ],
    steps: [
      'Fräs lök, vitlök och curry i olja.',
      'Tillsätt morot och paprika i bitar. Stek några minuter.',
      'Häll i kokosmjölk och buljong. Sjud femton minuter.',
      'Rör ner bönor och spenat sista fem minuterna. Koka ris till.',
    ],
  }),
]

/** Snabb uppslagning på id. */
export const SEED_RECIPES_BY_ID: ReadonlyMap<string, Recipe> = new Map(
  SEED_RECIPES.map((item) => [item.id, item]),
)
