-- Genererad av scripts/generate-seed.ts. Redigera inte för hand —
-- ändra src/domain/ingredients.ts och kör om skriptet.

insert into public.ingredients
  (id, name, canonical_unit, category, staple,
   piece_weight_g, piece_weight_min_g, piece_weight_max_g, grams_per_dl)
values
  ('blandfars', 'blandfärs', 'g', 'kott-fagel', false, null, null, null, null),
  ('notkott_gryta', 'grytbitar av nöt', 'g', 'kott-fagel', false, null, null, null, null),
  ('flaskkarre', 'fläskkarré', 'g', 'kott-fagel', false, null, null, null, null),
  ('flaskfile', 'fläskfilé', 'g', 'kott-fagel', false, null, null, null, null),
  ('kycklingfile', 'kycklingfilé', 'g', 'kott-fagel', false, null, null, null, null),
  ('kycklinglarfile', 'kycklinglårfilé', 'g', 'kott-fagel', false, null, null, null, null),
  ('bacon', 'bacon', 'g', 'chark', false, null, null, null, null),
  ('falukorv', 'falukorv', 'g', 'chark', false, 800, 700, 900, null),
  ('prinskorv', 'prinskorv', 'g', 'chark', false, null, null, null, null),
  ('skinka_tarnad', 'tärnad skinka', 'g', 'chark', false, null, null, null, null),
  ('flask_rimmat', 'rimmat fläsk', 'g', 'chark', false, null, null, null, null),
  ('laxfile', 'laxfilé', 'g', 'fisk', false, null, null, null, null),
  ('torskfile', 'torskfilé', 'g', 'fisk', false, null, null, null, null),
  ('rakor', 'räkor', 'g', 'fisk', false, null, null, null, null),
  ('gul_lok', 'gul lök', 'g', 'frukt-gront', false, 110, 80, 150, null),
  ('rodlok', 'rödlök', 'g', 'frukt-gront', false, 100, 70, 140, null),
  ('purjolok', 'purjolök', 'g', 'frukt-gront', false, 250, 180, 350, null),
  ('vitlok', 'vitlöksklyfta', 'g', 'frukt-gront', false, 3, 2, 5, null),
  ('potatis', 'potatis', 'g', 'frukt-gront', false, 100, 70, 140, null),
  ('morot', 'morot', 'g', 'frukt-gront', false, 85, 60, 120, null),
  ('palsternacka', 'palsternacka', 'g', 'frukt-gront', false, 130, 90, 180, null),
  ('kalrot', 'kålrot', 'g', 'frukt-gront', false, 700, 500, 1000, null),
  ('vitkal', 'vitkål', 'g', 'frukt-gront', false, 1200, 900, 1800, null),
  ('broccoli', 'broccoli', 'g', 'frukt-gront', false, 350, 250, 450, null),
  ('blomkal', 'blomkål', 'g', 'frukt-gront', false, 600, 450, 800, null),
  ('tomat', 'tomat', 'g', 'frukt-gront', false, 110, 80, 150, null),
  ('paprika', 'paprika', 'g', 'frukt-gront', false, 150, 120, 200, null),
  ('gurka', 'gurka', 'g', 'frukt-gront', false, 350, 280, 450, null),
  ('salladshuvud', 'salladshuvud', 'g', 'frukt-gront', false, 300, 200, 400, null),
  ('champinjoner', 'champinjoner', 'g', 'frukt-gront', false, null, null, null, null),
  ('majs', 'majs', 'g', 'konserver', false, null, null, null, null),
  ('citron', 'citron', 'g', 'frukt-gront', false, 100, 80, 130, null),
  ('persilja', 'persilja', 'g', 'frukt-gront', false, null, null, null, null),
  ('dill', 'dill', 'g', 'frukt-gront', false, null, null, null, null),
  ('graslok', 'gräslök', 'g', 'frukt-gront', false, null, null, null, null),
  ('mjolk', 'mjölk', 'ml', 'mejeri-agg', false, null, null, null, 103),
  ('vispgradde', 'vispgrädde', 'ml', 'mejeri-agg', false, null, null, null, 100),
  ('matlagningsgradde', 'matlagningsgrädde', 'ml', 'mejeri-agg', false, null, null, null, 100),
  ('creme_fraiche', 'crème fraiche', 'ml', 'mejeri-agg', false, null, null, null, 100),
  ('graddfil', 'gräddfil', 'ml', 'mejeri-agg', false, null, null, null, 100),
  ('smor', 'smör', 'g', 'mejeri-agg', true, null, null, null, null),
  ('margarin', 'margarin', 'g', 'mejeri-agg', false, null, null, null, null),
  ('ost_riven', 'riven ost', 'g', 'mejeri-agg', false, null, null, null, null),
  ('agg', 'ägg', 'g', 'mejeri-agg', false, 58, 53, 63, null),
  ('spaghetti', 'spaghetti', 'g', 'skafferi', false, null, null, null, null),
  ('pasta', 'pasta', 'g', 'skafferi', false, null, null, null, null),
  ('lasagneplattor', 'lasagneplattor', 'g', 'skafferi', false, null, null, null, null),
  ('ris', 'ris', 'g', 'skafferi', false, null, null, null, 85),
  ('vetemjol', 'vetemjöl', 'g', 'skafferi', true, null, null, null, 60),
  ('potatismjol', 'potatismjöl', 'g', 'skafferi', true, null, null, null, 70),
  ('strobrod', 'ströbröd', 'g', 'skafferi', true, null, null, null, 50),
  ('havregryn', 'havregryn', 'g', 'skafferi', false, null, null, null, 35),
  ('gula_artor', 'gula ärtor', 'g', 'skafferi', false, null, null, null, 85),
  ('socker', 'socker', 'g', 'skafferi', true, null, null, null, 85),
  ('salt', 'salt', 'g', 'skafferi', true, null, null, null, 120),
  ('peppar', 'svartpeppar', 'g', 'skafferi', true, null, null, null, 45),
  ('rapsolja', 'rapsolja', 'ml', 'skafferi', true, null, null, null, 92),
  ('buljongtarning', 'buljongtärning', 'g', 'skafferi', true, 10, 9, 12, null),
  ('soja', 'soja', 'ml', 'skafferi', true, null, null, null, 110),
  ('ketchup', 'ketchup', 'ml', 'skafferi', true, null, null, null, 110),
  ('senap', 'senap', 'ml', 'skafferi', true, null, null, null, 110),
  ('tomatpure', 'tomatpuré', 'g', 'konserver', false, null, null, null, 110),
  ('krossade_tomater', 'krossade tomater', 'g', 'konserver', false, null, null, null, null),
  ('kokosmjolk', 'kokosmjölk', 'ml', 'konserver', false, null, null, null, null),
  ('kidneybonor', 'kidneybönor', 'g', 'konserver', false, null, null, null, null),
  ('lingonsylt', 'lingonsylt', 'g', 'skafferi', false, null, null, null, null),
  ('curry', 'curry', 'g', 'skafferi', true, null, null, null, 40),
  ('paprikapulver', 'paprikapulver', 'g', 'skafferi', true, null, null, null, 40),
  ('timjan', 'timjan', 'g', 'skafferi', true, null, null, null, 20),
  ('oregano', 'oregano', 'g', 'skafferi', true, null, null, null, 20),
  ('lagerblad', 'lagerblad', 'g', 'skafferi', true, 0.2, 0.1, 0.3, null),
  ('kryddpeppar', 'kryddpeppar', 'g', 'skafferi', true, null, null, null, 45),
  ('chilipulver', 'chilipulver', 'g', 'skafferi', true, null, null, null, 40),
  ('spiskummin', 'spiskummin', 'g', 'skafferi', true, null, null, null, 40),
  ('tacokrydda', 'tacokrydda', 'g', 'skafferi', false, null, null, null, 40),
  ('vinager', 'ättika', 'ml', 'skafferi', true, null, null, null, 100),
  ('tortilla', 'tortillabröd', 'g', 'brod', false, null, null, null, null),
  ('knackebrod', 'knäckebröd', 'g', 'brod', false, null, null, null, null),
  ('arter_frysta', 'frysta ärter', 'g', 'frys', false, null, null, null, null),
  ('spenat_fryst', 'fryst spenat', 'g', 'frys', false, null, null, null, null)
on conflict (id) do update set
  name = excluded.name,
  canonical_unit = excluded.canonical_unit,
  category = excluded.category,
  staple = excluded.staple,
  piece_weight_g = excluded.piece_weight_g,
  piece_weight_min_g = excluded.piece_weight_min_g,
  piece_weight_max_g = excluded.piece_weight_max_g,
  grams_per_dl = excluded.grams_per_dl;

insert into public.ingredient_aliases (ingredient_id, alias)
values
  ('blandfars', 'köttfärs'),
  ('blandfars', 'nötfärs'),
  ('blandfars', 'färs'),
  ('blandfars', 'blandfärs 50/50'),
  ('notkott_gryta', 'grytbitar'),
  ('notkott_gryta', 'högrev'),
  ('notkott_gryta', 'nötkött i bitar'),
  ('flaskkarre', 'karré'),
  ('kycklingfile', 'kycklingbröstfilé'),
  ('kycklingfile', 'kyckling'),
  ('kycklinglarfile', 'kycklinglår'),
  ('kycklinglarfile', 'lårfilé'),
  ('skinka_tarnad', 'skinka'),
  ('skinka_tarnad', 'skinktärningar'),
  ('flask_rimmat', 'sidfläsk'),
  ('laxfile', 'lax'),
  ('torskfile', 'torsk'),
  ('torskfile', 'vit fisk'),
  ('gul_lok', 'lök'),
  ('gul_lok', 'lökar'),
  ('purjolok', 'purjo'),
  ('vitlok', 'vitlök'),
  ('vitlok', 'vitlöksklyftor'),
  ('potatis', 'fast potatis'),
  ('potatis', 'mjölig potatis'),
  ('morot', 'morötter'),
  ('tomat', 'tomater'),
  ('salladshuvud', 'sallad'),
  ('salladshuvud', 'isbergssallad'),
  ('champinjoner', 'svamp'),
  ('mjolk', 'mellanmjölk'),
  ('mjolk', 'standardmjölk'),
  ('mjolk', 'lättmjölk'),
  ('vispgradde', 'grädde'),
  ('margarin', 'bordsmargarin'),
  ('ost_riven', 'ost'),
  ('ost_riven', 'riven cheddar'),
  ('pasta', 'penne'),
  ('pasta', 'fusilli'),
  ('pasta', 'makaroner'),
  ('ris', 'långkornigt ris'),
  ('vetemjol', 'mjöl'),
  ('socker', 'strösocker'),
  ('peppar', 'peppar'),
  ('rapsolja', 'olja'),
  ('rapsolja', 'matolja'),
  ('buljongtarning', 'buljong'),
  ('buljongtarning', 'köttbuljong'),
  ('buljongtarning', 'grönsaksbuljong'),
  ('buljongtarning', 'hönsbuljong'),
  ('krossade_tomater', 'tomatkross'),
  ('krossade_tomater', 'finkrossade tomater'),
  ('lingonsylt', 'lingon'),
  ('lingonsylt', 'rårörda lingon'),
  ('vinager', 'vinäger'),
  ('arter_frysta', 'ärter'),
  ('arter_frysta', 'gröna ärter'),
  ('spenat_fryst', 'spenat')
on conflict do nothing;
